"""add cooling load coefficient

Revision ID: 111f08b9bb5d
Revises: c513cdc6b5e4
Create Date: 2025-02-11 00:13:07.053069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '111f08b9bb5d'
down_revision: Union[str, None] = 'c513cdc6b5e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooling_load_fast_coefficient',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('QUAI', 'CF', 'PLATEFORME', name='coldroomcategory'), nullable=False),
    sa.Column('vol_min', sa.Integer(), nullable=False),
    sa.Column('vol_max', sa.Integer(), nullable=False),
    sa.Column('coef', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cooling_load_fast_coefficient_category'), 'cooling_load_fast_coefficient', ['category'], unique=False)
    op.create_index(op.f('ix_cooling_load_fast_coefficient_id'), 'cooling_load_fast_coefficient', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cooling_load_fast_coefficient_id'), table_name='cooling_load_fast_coefficient')
    op.drop_index(op.f('ix_cooling_load_fast_coefficient_category'), table_name='cooling_load_fast_coefficient')
    op.drop_table('cooling_load_fast_coefficient')
    # ### end Alembic commands ###
