"""delete cooling fast load

Revision ID: 5cc1b5e7d596
Revises: 111f08b9bb5d
Create Date: 2025-02-16 11:36:36.470409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5cc1b5e7d596'
down_revision: Union[str, None] = '111f08b9bb5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cooling_load_fast_coefficient_category', table_name='cooling_load_fast_coefficient')
    op.drop_index('ix_cooling_load_fast_coefficient_id', table_name='cooling_load_fast_coefficient')
    op.drop_table('cooling_load_fast_coefficient')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooling_load_fast_coefficient',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('category', sa.VARCHAR(length=10), nullable=False),
    sa.Column('vol_min', sa.INTEGER(), nullable=False),
    sa.Column('vol_max', sa.INTEGER(), nullable=False),
    sa.Column('coef', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cooling_load_fast_coefficient_id', 'cooling_load_fast_coefficient', ['id'], unique=False)
    op.create_index('ix_cooling_load_fast_coefficient_category', 'cooling_load_fast_coefficient', ['category'], unique=False)
    # ### end Alembic commands ###
